[package]
name = "eip-operator"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.10"
aws-sdk-ec2 = "0.10"
aws-sdk-servicequotas = "0.10"
futures-util = "0.3"
json-patch = "0.2"
k8s-openapi = { version = "0.14", default-features = false, features = ["v1_21"] }
kube = { version = "0.70", features = ["derive"] }
kube-runtime = "0.70"
log = "0.4"
opentelemetry = { version = "0.17", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = { version = "0.10" }

tonic = { version = "0.6.2", features = ["transport"] }
tokio-native-tls = { version = "0.3.0" }
native-tls = { version = "0.2.10", features = ["alpn"] }
hyper-proxy = { version = "0.9.1" }
hyper = { version = "0.14.17", features = ["http2"] }
hyper-tls = { version = "0.5.0" }

rand = "0.8"
schemars = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
# for endpoints
http = "0.2.7"
aws-smithy-http = "0.40.2"
aws-types = "0.11"
