[package]
name = "eip-operator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.17-alpha", package = "aws-config" }
aws-sdk-ec2 = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.17-alpha", package = "aws-sdk-ec2" }
env_logger = "0.9"
futures-util = "0.3"
k8s-openapi = { version = "0.13", default-features = false, features = ["v1_19"] }
kube = "0.59"
kube-derive = "0.59"
kube-runtime = "0.60"
log = "0.4"
schemars = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
