[workspace]
members = [
    "eip_operator",
    "cilium_eip_no_masquerade_agent",
    "eip_operator_shared",
]

# Use this section only to change the source of dependencies that might
# also appear as transitive dependencies of other external dependencies in
# the dependency graph. For everything else set the `git` sourcce
# directly in each dependency entry.
[patch.crates-io]
# bump the opentelemetry deps for tonic to 0.7
opentelemetry = { git = "https://github.com/MaterializeInc/opentelemetry-rust.git" }
opentelemetry-otlp = { git = "https://github.com/MaterializeInc/opentelemetry-rust.git" }
