[package]
name = "eip-operator"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.8"
aws-sdk-ec2 = "0.6"
futures-util = "0.3"
json-patch = "0.2"
k8s-openapi = { version = "0.14", default-features = false, features = ["v1_21"] }
kube = { version = "0.69", features = ["derive"] }
kube-runtime = "0.69"
log = "0.4"
opentelemetry = { version = "0.17", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.10", default-features = false, features = ["grpc-sys", "openssl", "prost", "tokio"] }
rand = "0.8"
schemars = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }

[features]
default = ["opentelemetry-otlp/openssl-vendored"]
