[package]
name = "eip-operator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3"
k8s-openapi = { version = "0.12", default-features = false, features = ["v1_19"] }
kube = "0.58"
kube-derive = "0.58"
kube-runtime = "0.58"
rusoto_core = "0.47"
rusoto_credential = "0.47"
rusoto_ec2 = "0.47"
rusoto_sts = "0.47"
schemars = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
