[package]
name = "eip-operator"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.14"
aws-sdk-ec2 = "0.14"
aws-sdk-servicequotas = "0.14"
aws-smithy-http = "0.44"
futures-util = "0.3"
json-patch = "0.2"
k8s-openapi = { version = "0.15", default-features = false, features = ["v1_21"] }
kube = { version = "0.74", features = ["derive"] }
kube-runtime = "0.74"
log = "0.4"
opentelemetry = { version = "0.17", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = { version = "0.10" }

tonic = { version = "0.7.2", features = ["transport"] }
tokio-native-tls = { version = "0.3.0" }
native-tls = { version = "0.2.10", features = ["alpn"] }
hyper-proxy = { version = "0.9.1" }
hyper = { version = "0.14.19", features = ["http2"] }
hyper-tls = { version = "0.5.0" }

rand = "0.8"
schemars = "0.8"
serde = "1"
serde_json = "1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }

# Use this section only to change the source of dependencies that might
# also appear as transitive dependencies of other external dependencies in
# the dependency graph. For everything else set the `git` sourcce
# directly in each dependency entry.
[patch.crates-io]
# bump the opentelemetry deps for tonic to 0.7
opentelemetry = { git = "https://github.com/MaterializeInc/opentelemetry-rust.git" }
opentelemetry-otlp = { git = "https://github.com/MaterializeInc/opentelemetry-rust.git" }
