[package]
name = "cilium-eip-no-masquerade-agent"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
ipnetwork = "0.20"
k8s-openapi = { version = "0.15", default-features = false, features = ["v1_21"] }
kube = { git = "https://github.com/MaterializeInc/kube-rs.git", branch = "fix_duplicate_finalizers", features = ["derive"] }
kube-runtime = { git = "https://github.com/MaterializeInc/kube-rs.git", branch = "fix_duplicate_finalizers" }
rand = "0.8"
rtnetlink = { git = "https://github.com/MaterializeInc/netlink.git", branch = "priority_support" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tracing = "0.1"

eip-operator-shared = { path = "../eip_operator_shared" }
