[package]
name = "eip-operator-shared"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-ec2 = "0.15"
aws-sdk-servicequotas = "0.15"
aws-smithy-http = "0.45"
futures = "0.3"
hyper = { version = "0.14.20", features = ["http2"] }
hyper-tls = { version = "0.5.0" }
kube = { git = "https://github.com/MaterializeInc/kube-rs.git", branch = "fix_duplicate_finalizers", features = ["derive"] }
native-tls = { version = "0.2.10", features = ["alpn"] }
opentelemetry = { version = "0.17", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = { version = "0.10" }
serde = "1"
serde_json = "1"
thiserror = "1"
tokio-native-tls = { version = "0.3.0" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tonic = { version = "0.8.0", features = ["transport"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }

rtnetlink = { git = "https://github.com/MaterializeInc/netlink.git", branch = "priority_support" }
