[package]
name = "eip-operator-shared"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-ec2 = "0.21"
aws-sdk-servicequotas = "0.21"
aws-smithy-http = "0.51"
futures = "0.3"
hyper = { version = "0.14.20", features = ["http2"] }
hyper-tls = { version = "0.5.0" }
kube = { version = "0.75", features = ["derive"] }
kube-runtime = { version = "0.76" }
native-tls = { version = "0.2.11", features = ["alpn"] }
opentelemetry = { version = "0.17", features = ["rt-tokio", "trace"] }
opentelemetry-otlp = { version = "0.10" }
serde = "1"
serde_json = "1"
thiserror = "1"
tokio-native-tls = { version = "0.3.0" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
tonic = { version = "0.7.2", features = ["transport"] }
tracing = "0.1"
tracing-opentelemetry = "0.17"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter", "json"] }

rtnetlink = { git = "https://github.com/MaterializeInc/netlink.git", branch = "priority_support" }
async-trait = "0.1.59"
rand = "0.8.5"
