name: Tests
on:
  pull_request:

env:
  KUBECONFIG: /tmp/kubeconfig
  KIND_VERSION: "0.12.0"
  K8S_VERSION: "1.21.1"  # closest hub.docker.com/r/kindest/node version to our EKS deploy
  KUTTL_VERSION: "0.11.1"
  SHA: ${{ github.sha }}

jobs:
  local-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t materialize/k8s-eip-operator:${{ github.sha }} .

  integration:
    runs-on: ubuntu-20.04
    needs: local-build
    strategy:
      fail-fast: false

    env:
      KUBECONFIG: /tmp/kubeconfig

    steps:
      # Bash as default shell is needed by the kuttl tests
      - name: Set bash as default shell
        run: |
          echo 'APT::Acquire::Retries "5";' | sudo tee /etc/apt/apt.conf.d/80-retries
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y bash
          sudo ln -s bash /bin/sh.bash
          sudo mv /bin/sh.bash /bin/sh
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v${K8S_VERSION}/bin/linux/amd64/kubectl"
          sudo install ./kubectl /usr/local/bin/
          kubectl version --short --client
          kubectl version --short --client | grep -q ${K8S_VERSION}
      - name: Install KinD
        run: |
          curl -L -o kind https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64
          sudo install ./kind /usr/local/bin && rm kind
          kind version
          kind version | grep -q ${KIND_VERSION}
      - name: Install KUTTL
        run: |
          curl -L -o kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v${KUTTL_VERSION}/kubectl-kuttl_${KUTTL_VERSION}_linux_x86_64
          sudo install ./kubectl-kuttl /usr/local/bin && rm kubectl-kuttl
          kubectl kuttl version
          kubectl kuttl version | grep -q ${KUTTL_VERSION}
      - name: Set up Helm
        uses: azure/setup-helm@a517f2ff6560563a369e16ca7c7d136b6164423f
        with:
          version: v3.6.2
      - name: Push container to kuttl tests
        run: |
          echo "\nkindContainers:\n - materialize/k8s-eip-operator:${SHA}\n" >> kuttl-test.yaml
      - name: Validate test file yaml
        run: |
          cat kuttl-test.yaml
      - name: Run tests
        run: kubectl kuttl test -v=3
